const SocketMessageType = Object.freeze({
    MSG_TO_ALL_LOGGED: "MSG_TO_ALL_LOGGED",
    MSG_TO_ALL: "MSG_TO_ALL",
    OPEN_CONNECTION: "OPEN_CONNECTION",
    NEW_CONNECTION: "NEW_CONNECTION",
    NEW_DISCONNECTION: "NEW_DISCONNECTION",
    DEFAULT_MESSAGE: "DEFAULT_MESSAGE",
    ON_VIDEO_MSG: "ON_VIDEO_MSG",
    ON_LIVE_MSG: "ON_LIVE_MSG",
    TESTING: "TESTING",
    MSG_BATCH: "MSG_BATCH",
    UNDEFINED: "UNDEFINED"
});

module.exports = SocketMessageType;
